// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdIDbPmA-OP1dcw2vwInf1w46zSEKw78',
    appId: '1:1017624066475:web:1d7bbf733de0620e3a3aee',
    messagingSenderId: '1017624066475',
    projectId: 'aleefyapp-bb4fd',
    authDomain: 'aleefyapp-bb4fd.firebaseapp.com',
    storageBucket: 'aleefyapp-bb4fd.firebasestorage.app',
    measurementId: 'G-0ELF4J5TPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCTJa9nt3p2I1cUdLagBLeOLQYZM2kDA',
    appId: '1:1017624066475:android:76f598d7c3f872e63a3aee',
    messagingSenderId: '1017624066475',
    projectId: 'aleefyapp-bb4fd',
    storageBucket: 'aleefyapp-bb4fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhEZ0V5bP4CwniZtFrc-ddboKl2fOdPs',
    appId: '1:1017624066475:ios:d1d8fa8ffe39ee563a3aee',
    messagingSenderId: '1017624066475',
    projectId: 'aleefyapp-bb4fd',
    storageBucket: 'aleefyapp-bb4fd.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhEZ0V5bP4CwniZtFrc-ddboKl2fOdPs',
    appId: '1:1017624066475:ios:d1d8fa8ffe39ee563a3aee',
    messagingSenderId: '1017624066475',
    projectId: 'aleefyapp-bb4fd',
    storageBucket: 'aleefyapp-bb4fd.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARdIDbPmA-OP1dcw2vwInf1w46zSEKw78',
    appId: '1:1017624066475:web:cba2393565f77c963a3aee',
    messagingSenderId: '1017624066475',
    projectId: 'aleefyapp-bb4fd',
    authDomain: 'aleefyapp-bb4fd.firebaseapp.com',
    storageBucket: 'aleefyapp-bb4fd.firebasestorage.app',
    measurementId: 'G-21ED0MS9GX',
  );
}
